spring.application.name=product-service
server.port=8081

# Actuator Config
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

api.key=${API_KEY:secret-api-key}
logging.level.com.linktic=DEBUG

inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8082}
spring.cloud.openfeign.httpclient.hc5.enabled=true

# Resilience4j Config
resilience4j.circuitbreaker.instances.inventoryService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.inventoryService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.eventConsumerBufferSize=10

resilience4j.retry.instances.inventoryService.maxAttempts=3
resilience4j.retry.instances.inventoryService.waitDuration=2s
resilience4j.retry.instances.inventoryService.enableExponentialBackoff=true
resilience4j.retry.instances.inventoryService.exponentialBackoffMultiplier=2